dataset: "agingTTS_22kHz"

path:
  corpus_path: "./agingTTS_22kHz"
  lexicon_path: "lexicon/english_us_mfa.dict" # Path to the lexicon
  df_path: "./agingTTS.txt" # Path to the dataframe with age information
  raw_path: "./agingTTS_22kHz" # Path to the folder with wav and lab files
  preprocessed_path: "./preprocessed_data/agingTTS_22kHz" # Path to the folder with TextGrids, where to save preprocessed data (duration, energy, etc)

preprocessing:
  val_size: 512
  text:
    text_cleaners: []
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
